[package]
name = "data_processing"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
diesel = "2.3.1"
markdown = "1.0.0"
nom = "8.0.0"
anyhow = "1.0.99"
thiserror = "2.0.16"
log = "0.4.28"
